# Generated by Django 4.1.3 on 2022-12-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('space_available', models.IntegerField()),
                ('day', models.CharField(choices=[('Monday', 1), ('Tuesday', 2), ('Wednesday', 3), ('Thursday', 4), ('Friday', 5), ('Saturday', 6), ('Sunday', 7)], max_length=80)),
                ('length', models.CharField(choices=[('Weekly', 1), ('Biweekly', 2), ('Monthly', 3)], max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_cancelled', models.BooleanField()),
                ('is_enrolled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('Classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='classes.class')),
            ],
        ),
    ]
